# Generated by Django 2.1.7 on 2019-11-19 13:35

import Events.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=255)),
                ('eventDescription', models.TextField()),
                ('eventDate', models.DateField()),
                ('eventDatetime', models.DateTimeField()),
                ('eventTime', models.TimeField()),
                ('user', models.ForeignKey(blank=True, default=Events.models.defaultUser, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
