# Generated by Django 2.1.7 on 2019-11-20 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20191119_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
