# Generated by Django 2.1.7 on 2019-11-20 15:08

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_remove_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='28.6024, 81.2001', max_length=63),
        ),
    ]
