# Generated by Django 2.2.7 on 2019-11-20 16:19

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='28.6024, -81.2001', max_length=63),
        ),
    ]
