# Generated by Django 2.1.7 on 2019-11-20 16:01

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20191120_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='28.6024, -81.2001', max_length=63),
        ),
    ]
