# Generated by Django 2.2.7 on 2019-11-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20191120_1119'),
        ('Events', '0007_auto_20191120_1101'),
    ]

    operations = [
    ]
