# Generated by Django 2.1.7 on 2019-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20191120_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isRSO',
            field=models.BooleanField(default=False),
        ),
    ]
