# Generated by Django 2.1.7 on 2019-11-20 14:33

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0001_initial'),
        ('Users', '0003_auto_20191120_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('universities', models.ManyToManyField(default=Users.models.defaultUser, to='Universities.University')),
            ],
        ),
    ]
